### ISSUE TITLE
Why not indent_size 2

### ISSUE THREAD

**Issue by mperkh** [radum/webapp-boilerplate#2]
Very nice boilerplate. Do you consider changing indent_size = 4 to 2? While its no problem for the enduser to switch to 2, but on notebooks indent_size = 2 makes more sense.

**Comment by radum** [comment]
Thanks 👍 , I manly built this for my own use, happy to see other find it useful.

I use tabs because of [all these reasons](http://lea.verou.me/2012/01/why-tabs-are-clearly-superior/).

And a tab char can be customized to have whatever length you want, so that, for me, is even more powerful.

Take a look at the jQuery src, they use tabs and everyone is happy with it.
